apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: minio-secret
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: update-service-config