apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: http://localhost:3000