apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Never # this will pull the image from the local repository