apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelgen
  labels:
    app: otelgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelgen
  template:
    metadata:
      name: otelgen
      labels:
        app: otelgen
    spec:
      containers:
        - name: otelgen-traces
          image: ghcr.io/krzko/otelgen:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--otel-exporter-otlp-endpoint"
            - "alloy.alloy.svc.cluster.local:4317"
            - "--insecure"
            - "--duration"
            - "86400"
            - "--rate"
            - "10"
            - "traces"
            - "multi"
        - name: otelgen-metrics
          image: ghcr.io/krzko/otelgen:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--otel-exporter-otlp-endpoint"
            - "alloy.alloy.svc.cluster.local:4317"
            - "--insecure"
            - "metrics"
            - "histogram"
      restartPolicy: Always
      