apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 5m
  releaseName: tempo
  chart:
    spec:
      chart: charts/tempo
      sourceRef:
        kind: GitRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      reportingEnabled: false
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://mimir-distributor.mimir.svc.cluster.local/api/v1/push"
      overrides:
        defaults:
          metrics_generator:
            processors: [ local-blocks ]
      extraArgs:
        "-config.expand-env": "true"
