apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: grafana
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1XEAEOc=,iv:ssCR8QzwPAxD/AUh/x5guGOwVju8HY7jFgQ6p5pxiTc=,tag:IpZD6O/sU707zKOy7ry2MQ==,type:str]
    password: ENC[AES256_GCM,data:0WOowg==,iv:y1AToM00JoYL+2pljs4JWCjMSpOLgZLP8Wvsd0n3kHM=,tag:WocgXT27EdrBQfI2nWVhSg==,type:str]
sops:
    age:
        - recipient: age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSlB5S2k1L25SUCs5SEZD
            NWcxa1ByMmxFRTRxKzZPb0x2bmJsSnVZQUFjCnVmK2wxQXlXRHE0eVM2T3RBSlZL
            RzJhSHVITm44ZVdXMExGQko2anQySDQKLS0tIG53MXA0UEltczZFZ202b3A5TDNt
            bExxQkdTcGl3bnM2T2JESW1VMWk1YXMKj9H+Kf+rIEsfAr2RLTkK/UDflri82Vq5
            y249l41lDn9YDpBCx6pbSTh3EjHLLcA1+aEM6zlc7N3g5ms1Iw366w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T08:17:01Z"
    mac: ENC[AES256_GCM,data:yq7O9SkIORJ9bm14vHJ2d4g5bz8X1tc+Ew+yxCLawneqAaYjrLeYUkBb7KuBBWzQbdHbNSAp9RBIx6Ey7pQ3OCQQMzCTVFbTBND9cLq+UnZyVymJqCFkWH6Qy3DSOBv3jiG8Aw32JRLTxiZ/o0tHNKxa+iUf4ia3y8ZBuhF0zg0=,iv:fMo0AH94SIK2MrRsfiCZnfHnic+8X0Q1OsofQMlPao4=,tag:YZNH8Tosxad7HK7Qn3wbxw==,type:str]
    encrypted_regex: ^(data|stringData|values)$
    version: 3.10.2
