creation_rules:
  - name: local
    path_regex: '(apps|infrastructure|clusters)/local/.*.yaml'
    encrypted_regex: '^(data|stringData|values)$'
    age: 'age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j'
  - name: prod
    path_regex: '(apps|infrastructure|clusters)/prod/.*.yaml'
    encrypted_regex: '^(data|stringData|values)$'
    age: 'age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j'
