apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  releaseName: alloy
  targetNamespace: alloy
  chart:
    spec:
      chart: operations/helm/charts/alloy
      sourceRef:
        kind: GitRepository
        name: alloy
        namespace: flux-system

  values:
    alloy:
      configMap:
        create: false
        content: ''
        name: alloy
        key: config.alloy
      mounts:
        # -- Mount /var/log from the host into the container for log collection.
        varlog: true
      extraPorts:
        - targetPort: 4317
          port: 4317
          name: otlp-grpc
    controller:
      priorityClassName: system-cluster-critical
