apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 28.0.0
  targetNamespace: kube-system
  valuesContent: |
    image:
      tag: "v3.5.0"
    
    # Configure ports properly for the Traefik Helm chart
    ports:
      web:
        port: 80
        # Remove expose config - let chart defaults handle it
      websecure:
        port: 443
        # Remove expose config - let chart defaults handle it
      traefik:
        port: 9000
      metrics:
        port: 9100
    
    # Use additionalArguments (not deployment.additionalArguments)
    additionalArguments:
      - --global.checknewversion
      - --global.sendanonymoususage
      - --api.dashboard=true
      - --ping=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entrypoint=metrics
      - --providers.kubernetescrd
      - --providers.kubernetesingress
      - --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik
      - --entrypoints.websecure.http.tls=true
      - --providers.kubernetesgateway
    
    service:
      type: ClusterIP