apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 28.0.0
  targetNamespace: kube-system
  valuesContent: |
    image:
      tag: "v3.5.0"
    
    ports:
      web:
        port: 80
      websecure:
        port: 443
      traefik:
        port: 9000
      metrics:
        port: 9100
    
    additionalArguments:
      - --providers.kubernetesgateway
    
    service:
      type: ClusterIP