apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
patches:
  - path: patch-enable-gateway.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: traefik
      namespace: kube-system
