apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-prod
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/prod/podinfo"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: podinfo
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
