apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhd-cloud-backend
  labels:
    app.kubernetes.io/name: dhd-cloud
    app.kubernetes.io/instance: dhd-cloud
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhd-cloud
      app.kubernetes.io/instance: dhd-cloud
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhd-cloud
        app.kubernetes.io/instance: dhd-cloud
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: 10.0.12.126:5000/dhd-cloud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dhd-cloud-config
      restartPolicy: Always
