apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-api
      version: "1.0.0"  # Use the latest stable version
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
