apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhd-cloud
  namespace: dhd-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhd-cloud
  template:
    metadata:
      labels:
        app: dhd-cloud
    spec:
      containers:
        - name: dhd-cloud
          image: 10.0.12.126:5000/dhd-cloud:latest
          ports:
            - containerPort: 8000
              name: http
