apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: dhd-cloud
  app.kubernetes.io/instance: dhd-cloud
