apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  values:
    tempo:
      extraEnvFrom:
        - secretRef:
            name: minio-secret
      storage:
        trace:
          # tempo storage backend.
          # Refers to: https://grafana.com/docs/tempo/latest/configuration/#storage
          ## Use s3 for example
          backend: s3
          # store traces in s3
          s3:
            bucket: tempo-traces
            endpoint: minio.minio:9000
            region: us-east-1
            bucket_lookup_type: 2 # BucketLookupPath
            access_key: ${MINIO_USERNAME}
            secret_key: ${MINIO_SECRET}
            insecure: true