apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service-backend
  labels:
    app.kubernetes.io/name: update-service
    app.kubernetes.io/instance: update-service
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: update-service
      app.kubernetes.io/instance: update-service
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: update-service
        app.kubernetes.io/instance: update-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: 10.0.12.126:5000/update-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: update-service-config
      restartPolicy: Always
      