apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: charts/grafana
      sourceRef:
        kind: GitRepository
        name: grafana
        namespace: default
  values:
    admin:
      # Name of the secret. Can be templated.
      existingSecret: "grafana-admin-secret"
      userKey: user
      passwordKey: password

    ## Configure grafana datasources
    ## ref: http://docs.grafana.org/administration/provisioning/#datasources
    ##
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki-gateway.loki.svc.cluster.local/
            basicAuth: false
            isDefault: false
            version: 1
            uid: loki
            editable: false
            tlsSkipVerifyInsecure: true
            jsonData:
              derivedFields:
                # Field with internal link pointing to data source in Grafana.
                - datasourceUid: tempo
                  matcherType: label
                  matcherRegex: traceId
                  name: TraceID
                  # url will be interpreted as query for the datasource
                  url: '$${__value.raw}'
                  urlDisplayLabel: View Trace

          - name: Tempo
            type: tempo
            access: proxy
            orgId: 1
            url: http://tempo.tempo.svc.cluster.local:3200/
            basicAuth: false
            isDefault: false
            version: 1
            uid: tempo
            tlsSkipVerifyInsecure: true
            jsonData:
              tracesToLogsV2:
                datasourceUid: loki
                spanStartTimeShift: '-30m'
                tags: [{ key: "service.name", value: "service_name" }]
                spanEndTimeShift: '30m'
                filterByTraceID: true
                filterBySpanID: false

          - name: Mimir
            type: prometheus
            access: proxy
            orgId: 1
            url: http://mimir-nginx.mimir.svc.cluster.local/prometheus/
            basicAuth: false
            isDefault: true
            version: 1
            uid: mimir
            tlsSkipVerifyInsecure: true
            jsonData:
              exemplarTraceIdDestinations:
                - name: traceId
                  datasourceUid: tempo
