apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhd-cloud
  namespace: dhd-cloud
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dhd-cloud
          env:
            - name: APP_ENVIRONMENT
              value: "local"
