apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/dhd-cloud
  - dhd-cloud-public-key.yaml
  - dhd-cloud-private-key.enc.yaml
  - postgres-secret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml