apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  values:
    # Disable loki-canary:
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      serviceMonitor:
        enabled: false
      lokiCanary:
        enabled: false

    loki:
      schemaConfig:
        configs:
          - from: '2024-04-01' # do not remove single quotes or flux will expand to a timestamp
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      auth_enabled: false
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          endpoint: minio.minio:9000
          s3ForcePathStyle: true
          region: us-east-1
          accessKeyId: ${MINIO_USERNAME}
          secretAccessKey: ${MINIO_SECRET}
          insecure: true
    deploymentMode: SingleBinary
    singleBinary:
      extraEnvFrom:
        - secretRef:
            name: minio-secret