apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  storage.server: |
    storage.cloud.dhd.intranet {
        rewrite name storage.cloud.dhd.intranet traefik-gateway.kube-system.svc.cluster.local
        forward . /etc/resolv.conf
    }
