apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  targetNamespace: minio
  chart:
    spec:
      chart: minio
      version: "14.7.12"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication
    auth:
      existingSecret: minio-secret
      rootUserSecretKey: "MINIO_ROOT_USER"
      rootPasswordSecretKey: "MINIO_ROOT_PASSWORD"

    # Default buckets
    defaultBuckets: "update-service,loki-chunks,loki-ruler,loki-admin,mimir-blocks,mimir-alertmanager,mimir-ruler,tempo-traces"

    # Disable persistence for testing
    persistence:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001

    # Resource limits
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 100m

    # Deployment configuration
    deployment:
      updateStrategy:
        type: Recreate

    # Health check configuration
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet:
        path: /minio/health/live
        port: api
        scheme: HTTP

    readinessProbe:
      enabled: true
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet:
        path: /minio/health/ready
        port: api
        scheme: HTTP

    # Security context
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop: ["ALL"]

    podSecurityContext:
      enabled: true
      fsGroup: 1001

    # Network policy (optional)
    networkPolicy:
      enabled: false