apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  values:
    defaultBuckets: "update-service, loki-chunks, loki-ruler, loki-admin, mimir-blocks, mimir-alertmanager, mimir-ruler, tempo-traces"
    persistence:
      enabled: false
    auth:
      existingSecret: minio-secret
      rootUserSecretKey: "MINIO_ROOT_USER"
      rootPasswordSecretKey: "MINIO_ROOT_PASSWORD"
