apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  targetNamespace: minio
  timeout: 10m
  chart:
    spec:
      chart: minio
      version: "14.7.12"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication
    auth:
      rootUser: "admin"
      rootPassword: "1111"

    # Remove default buckets - we'll create them later
    # defaultBuckets: ""

    # Disable persistence for testing
    persistence:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001

    # Resource limits
    resources:
      limits:
        memory: 512Mi
        cpu: 250m
      requests:
        memory: 256Mi
        cpu: 100m

    # Health probes with longer delays
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6
      httpGet:
        path: /minio/health/live
        port: api

    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      httpGet:
        path: /minio/health/ready
        port: api

    # Set mode to standalone
    mode: standalone

    # Disable extra features
    ingress:
      enabled: false
    metrics:
      enabled: false
    networkPolicy:
      enabled: false

    # Deployment strategy
    updateStrategy:
      type: Recreate