apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  targetNamespace: minio
  timeout: 10m
  chart:
    spec:
      chart: minio
      version: "14.7.12"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication - using direct values for simplicity
    auth:
      rootUser: "admin"
      rootPassword: "1111"

    # Default buckets (space-separated, not comma-separated for Bitnami chart)
    defaultBuckets: "update-service loki-chunks loki-ruler loki-admin mimir-blocks mimir-alertmanager mimir-ruler tempo-traces"

    # Disable persistence for testing
    persistence:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001

    # Resource limits
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 100m

    # Simplified probe configuration
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 6

    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 6

    # Set mode to standalone (single node)
    mode: standalone

    # Disable extra features that might cause issues
    ingress:
      enabled: false

    metrics:
      enabled: false

    networkPolicy:
      enabled: false