apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  targetNamespace: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication configuration
    auth:
      existingSecret: minio-secret
      rootUserSecretKey: "MINIO_ROOT_USER"
      rootPasswordSecretKey: "MINIO_ROOT_PASSWORD"
    
    # Persistence configuration - disable for local testing
    persistence:
      enabled: false
    
    # Disable all provisioning and client operations
    provisioning:
      enabled: false
    
    # Disable default bucket creation to avoid client issues
    defaultBuckets: ""
    
    # Service configuration
    service:
      type: ClusterIP
    
    # Completely disable health checks temporarily to let container start
    livenessProbe:
      enabled: false
    
    readinessProbe:
      enabled: false
    
    # Minimal resource requirements
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
    
    # Force single-node mode
    mode: standalone
    
    # Additional environment variables to ensure proper startup
    extraEnvVars:
      - name: MINIO_BROWSER
        value: "on"
      - name: MINIO_SERVER_URL
        value: "http://localhost:9000"
