
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  releaseName: minio
  targetNamespace: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication configuration
    auth:
      existingSecret: minio-secret
      rootUserSecretKey: "MINIO_ROOT_USER"
      rootPasswordSecretKey: "MINIO_ROOT_PASSWORD"

    # Persistence configuration
    persistence:
      enabled: false

    # Disable provisioning to avoid the mc client loop
    provisioning:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001

    # Adjusted health check timing
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6

    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3

    # Resource configuration
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"