apiVersion: v1
kind: Secret
metadata:
    name: podinfo-values
    namespace: podinfo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:XxP0ZV/fgkaYQIAqoisXdjr5i2+Ei72O1sgZ6JP0/1CjquE2lJVvPmevcd85Dnb/EkiDi+Vnjkg9q7s=,iv:ZldGYiagfpcmP9Oc27xkBPvQnkyYd7Urqa8fY3s8if8=,tag:OtFU9nblxlOkQB6Tv9beqQ==,type:str]
sops:
    age:
        - recipient: age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTGZkeCt2ZFRBTUZyR2tE
            TnZ5c1pwUHduQ1BNcTFaMUxzOVl4S3hIVkFNCkROVlAwdStCUU9ta3dxeDJHWVpp
            QUZoUEd0M2lCZnh1Tk5SdHorUElVVGsKLS0tIE9VM1R1MkxMS0h1T1VUSkRHZlhw
            V0RiRlJKSG5pTlphMGl1cFJKTkN5RXMKASWSlUAXg54GHnmPzHs1V19iU28x7Iy+
            34fOTSy2DMfl5kbgdoRUjhtpMVctz+BWuLjNh/CyVvMBHvjL+oFb9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T12:54:28Z"
    mac: ENC[AES256_GCM,data:011sK5qWGtwp5oq+2Zd9v5oiOVeoHLzMLFpTkpXZGkmRX9HMZ+BRfGPQzMqSaWJ5MqeCFMngxIt+FZ+mILAGUYA5QpqdI8xireHm9bJj1izUai/T3zs6W77mxlg81RYlY4XWu8gdwH7lPgkZhHeI0CGI2nmAbTRMtWEUMJ2iCqE=,iv:xoHbekV9+d4VjaUYguJlBGqSgIV0Dis/8OsApcSdYfA=,tag:5b3kYs27uGz6cSBOFFUqIA==,type:str]
    encrypted_regex: ^(data|stringData|values)$
    version: 3.10.2
