apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service-frontend
  labels:
    app.kubernetes.io/name: update-service
    app.kubernetes.io/instance: update-service
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: update-service
      app.kubernetes.io/instance: update-service
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: update-service
        app.kubernetes.io/instance: update-service
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: 10.0.12.126:5000/update-service-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      