apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: podinfo
        namespace: default
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: podinfo
                env:
                  - name: PODINFO_UI_COLOR
                    value: "orange"
                  - name: PODINFO_UI_MESSAGE
                    value: "Welcome to Podinfo (prod)!"
                  - name: PODINFO_BACKEND_URL
                    value: ""
                resources:
                  requests:
                    cpu: 20m
                    memory: 32Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi
