apiVersion: v1
kind: Secret
metadata:
    name: podinfo-values
    namespace: podinfo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:fzhgi/CtiSW673YdJtAPGToOI7TlZdKny7n3KNu1FCFDt9ZSDwp4EaeNus2YeHcNBGPIkFYE43ZYhA==,iv:fdORg4y2rhBJGenAyqf5VdIm371Oefk+AGSbaMcCcKY=,tag:oWIS8tJdpN6eGdMU3U1H5Q==,type:str]
sops:
    age:
        - recipient: age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZHlmdHZRUGxDNzM5Rmlu
            V3owWWQ4dHYzd2ZkeHk1cDJZMWluNlpmVlFBCkVYdUY4ZUV2b09yMC9zQzdKeUI0
            SW00ZDRMMWhIUisyVWxLalpqUTIxbE0KLS0tIHdWUFpJM1ZRUjFkV3l2WWIyQ2FS
            dkZpbE9QM0VEMnltTzdzOCtvTG5xREUKLmaTuWAirFsnZj3LRgSPr2VBXBO2KYE6
            V+oXEGvAb+Jqc2a3Ty0Mw1hxaRaBzyAESpgtSLl0OPaf2MN4EXgKHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T12:53:49Z"
    mac: ENC[AES256_GCM,data:6r8pxrkasu8O4TRlS2nFQuyTT8KwaeiaMQjG3ewDTu0uLfSjcQE4xt0g1Qf0NfzGbvG5C42bGboemWwoaH5eO4qaEe+9KGWI3GWc+eSuHuIyuw096OBH85uLdA/R0vjJBWJWswaeJIk2damihpQe5+ccjUPWYbfRB3KoQxnOOgI=,iv:IlwPmfWBYeGgRgTBB3kQZtPDz3ua6k6RWdHbur6N25g=,tag:9OhsLCgsJDsx8HyRWYtL9A==,type:str]
    encrypted_regex: ^(data|stringData|values)$
    version: 3.10.2
