apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
        prometheus.io/path: "/metrics"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9898"
      prometheus.io/path: "/metrics"
  valuesFrom:
    - kind: Secret
      name: podinfo-values
      valuesKey: values.yaml
#    replicaCount: 1
#    ui:
#      message: "Hello from Flux CD (base)!"
