apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "alloy.alloy.svc.cluster.local:4317"  # Replace with your actual OTLP endpoint
      - name: OTEL_SERVICE_NAME
        value: "podinfo"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=podinfo,service.version=6.x"
  valuesFrom:
    - kind: Secret
      name: podinfo-values
      valuesKey: values.yaml
#    replicaCount: 1
#    ui:
#      message: "Hello from Flux CD (base)!"
