apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    # Simple Mimir configuration for single-instance deployment
    target: all
    
    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      log_level: info
    
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data
    
    ingester:
      ring:
        kvstore:
          store: inmemory
    
    distributor:
      ring:
        kvstore:
          store: inmemory
    
    store_gateway:
      sharding_ring:
        kvstore:
          store: inmemory
    
    compactor:
      sharding_ring:
        kvstore:
          store: inmemory
    
    ruler:
      ring:
        kvstore:
          store: inmemory
    
    alertmanager:
      sharding_ring:
        kvstore:
          store: inmemory
    
    limits:
      ingestion_rate: 100000
      ingestion_burst_size: 200000