apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    deploymentMode: SingleBinary

    loki:
      schemaConfig:
        configs:
          - from: 2024-04-01
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 2

    # Disable multi-tenancy
    auth_enabled: false

    # Storage configuration
    chunksCache:
      # Disable chunks cache to reduce memory usage in single binary mode
      enabled: false
    resultsCache:
      # Disable results cache to reduce memory usage in single binary mode
      enabled: false

    # Gateway configuration
    gateway:
      enabled: true
      replicas: 1
      service:
        type: ClusterIP
        port: 80

    # Backend configuration - single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      persistence:
        enabled: true
        size: 10Gi

    # Monitoring
    monitoring:
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false

    # Test pods
    test:
      enabled: false
