apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  releaseName: loki
  chart:
    spec:
      chart: charts/loki/loki-6.29.0.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    loki:
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 2
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        # Keep a little bit lower than memory limits
        - name: GOMEMLIMIT
          value: 900MiB
    chunksCache:
      # default is 500MB, with limited memory keep this smaller
      writebackSizeLimit: 10MB
      allocatedMemory: 1024
      resources:
        requests:
          cpu: 250m
    resultsCache:
      # default is 500MB, with limited memory keep this smaller
      writebackSizeLimit: 10MB
      allocatedMemory: 512
      resources:
        requests:
          cpu: 250m

    # Enable minio for storage
    minio:
      enabled: false

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
