apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false

      # Use the built-in test schema to avoid date parsing issues
      useTestSchema: true

      commonConfig:
        replication_factor: 1

      storage:
        type: filesystem

      ingester:
        chunk_encoding: snappy
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1

      tracing:
        enabled: false

      querier:
        max_concurrent: 2

    # Storage configuration
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Gateway configuration
    gateway:
      enabled: true
      replicas: 1
      service:
        type: ClusterIP
        port: 80

    # Backend configuration - single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      persistence:
        enabled: true
        size: 10Gi
      extraEnv:
        - name: GOMEMLIMIT
          value: "900MiB"

    # Monitoring
    monitoring:
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false

    # Test pods
    test:
      enabled: false