apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1

      storage:
        type: filesystem

    # Storage configuration
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Gateway configuration
    gateway:
      enabled: true
      replicas: 1

    # Backend configuration - single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Single binary configuration
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi

    # Test pods
    test:
      enabled: false
